---
- name: Ensure ansible_facts used by role
  setup:
    gather_subset: "{{ __selinux_required_facts_subsets }}"
  when: __selinux_required_facts |
    difference(ansible_facts.keys() | list) | length > 0

- name: Install SELinux python2 tools
  package:
    name:
      - libselinux-python
      - policycoreutils-python
    state: present
  when: ansible_python_version is version('3', '<')

- name: Install SELinux python3 tools
  package:
    name:
      - libselinux-python3
      - policycoreutils-python3
    state: present
  when: ansible_python_version is version('3', '>=')

- name: Refresh facts
  setup:
    filter: ansible_selinux
  when: not __selinux_setup_snapshot | d(false)

- name: Install SELinux tool semanage
  package:
    name:
      - policycoreutils-python-utils
    state: present
  when: ansible_distribution == "Fedora" or
    (ansible_distribution_major_version | int > 7 and
     ansible_distribution in ["CentOS", "RedHat", "Rocky"])
